include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: true
    avoid_print: true
    unnecessary_string_interpolations: true
    sort_child_properties_last: true
    prefer_final_fields: true
    use_build_context_synchronously: false
    non_constant_identifier_names: false
    prefer_typing_uninitialized_variables: false